project_id = "etsaleegdpswwsprwyzv"

[functions.admin-api]
verify_jwt = false

[functions.daily-backup]
verify_jwt = false

[functions.restore-backup]
verify_jwt = false

[functions.machine-webhook]
verify_jwt = false